### test home page
GET http://localhost:8801/

### start API POST
POST http://localhost:8801/default/api/v1/workflow/start
Content-Type: application/json

{
  "workflowId": "test-wf",
  "iwfWorkflowType": "test-wf-type",
  "workflowTimeoutSeconds": 10,
  "iwfWorkerUrl": "http://localhost:8080",
  "startStateId": "test_state_1",
  "stateInput": {
    "encoding": "json",
    "data": "\"a string\""
  }
}

### reset API
### NOTE: supported resetType: BEGINNING, HISTORY_EVENT_ID, HISTORY_EVENT_TIME, STATE_ID, STATE_EXECUTION_ID
### each reset type may require one supplement field, e.g. HISTORY_EVENT_ID requires historyEventId
POST https://iwf-service.net/ihp-workflow-rsvp/api/v1/workflow/reset
Content-Type: application/json

{
  "workflowId": "2b85e588-12fd-456d-ad99-df51bda6cce8",
  "resetType": "STATE_ID",
  "stateId": "WaitAndPrepareState",
  "skipSignalReapply": true
}

### skip timer API
POST https://iwf-service.net/ihp-workflow-rsvp/api/v1/workflow/timer/skip
Content-Type: application/json

{
  "workflowId": "2b85e588-12fd-456d-ad99-df51bda6cce8",
  "workflowStateExecutionId": "WaitAndPrepareState-1",
  "timerCommandIndex": 0
}

### signal workflow
POST https://iwf-service.net/ihp-workflow-rsvp/api/v1/workflow/signal
Content-Type: application/json

{
  "workflowId": "3d8659b1-b985-4b50-9350-e34bdfee2b95",
  "signalChannelName": "sendNow",
  "signalValue": {
    "encoding": "jsonType",
    "data": "\"a string value\""
  }
}
