/*
 * Workflow APIs
 *
 * This APIs for iwf SDKs to operate workflows
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

import (
	"github.com/gin-gonic/gin"
)

const WorkflowStartApiPath = "/api/v1/workflow/start"

// NewService returns a new router.
func NewService() *gin.Engine {
	router := gin.Default()

	handler := newHandler()

	router.GET("/", handler.index)
	router.POST(WorkflowStartApiPath, handler.apiV1WorkflowStartPost)

	return router
}
